---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.1
env:
  global:
    - BEAKER_PUPPET_COLLECTION=puppet6 PUPPET_GEM_VERSION="~> 6.0"
stages:
  - static
  - spec
  - beaker
  -
    if: tag =~ ^v\d
    name: deploy
matrix:
  fast_finish: true
  include:
    -
      bundler_args: --with system_tests
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=debian-9 BEAKER_TESTMODE=apply
      rvm: 2.5.1
      script: bundle exec rake beaker
      services: docker
      stage: beaker
      sudo: required
    -
      env: CHECK="syntax lint metadata_lint"
      stage: static
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file"
      stage: static
    -
      env: CHECK="rubocop"
      stage: static
    -
      env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec
      rvm: 2.1.9
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.4
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.1
      stage: spec
    -
      env: CKECK=build DEPLOY_TO_FORGE=yes
      stage: deploy
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: trepasi
  password:
    secure: "GN+wkLalXykVgGxjRgMbbTxTq1nOmiSQYCe8Ap/VCPHKgn4VMmopQclE/+CwlJOzJGBfAKDvxoQX0AeVbbC0V4J5iWPtSXZcjxqaGySfNF0pA2aPF5NltAAM59SBt9hqdzfiV9zsdD7ilg1JunsLd6q9M5XXE5XfB2rLleSn/1RNZyLBuPijBepasDXASIkSO9WleOKBQY5lNHn0tpcnOc69o34mMTKPpv4hopX8rOANwpi4ks+u4xZBXEVm07X7u9OnMbgRWYrHdoEy9DQ2dSIKKkhjNSbL16zrvCG9KYcDfm9iOwJWEMwCmoXrpq8XgD+T/xbm13nNE/KR5+XzY4dep1YodSN/yIouskzdWJiWJTHe9LwdlWBPsmh+KEog2uHL9P3itNDiKeWFYSKwsJq2xoXfP6l85OhZyKzH0cFBpoX1f4ezlmyiBzHvyKJ7M/z4X74JfJLncnXazFrDQXN5U5+T6ag8P/eztZxVYRZuGob5+mUZm4Ye/sFTU+lV5ZI1N1N5XSXG1rmrwMJ93TWSH3CBjY/qNMH56jhnfcEWe3Vb1bkHhjBEBOproqCftfxpZSdmXLRN7e5RkXbSWtOf0JnOE5UFPAbb/rLPEnjtETTMmR3dysQIU+39jnRXtGr95M3LNhkpm/rTtGyCBYWzp8P++2eMztuM1fSN6+M="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
